#!/usr/bin/env bash
# Permanently redirecting requests to another page

# Install nginxi in the server
sudo apt update
sudo apt install -y nginx

sudo sed -i "53s/.*location \/redirect_me {\n\treturn 301 http:\/\/github.com\/\;\n}/" /etc/nginx/sites-available/default

# Start nginx server
sudo service nginx restart
