#!/usr/bin/env bash
# Permanently redirecting requests to another page

# Install Nginx
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service ngix start
newlines="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "53i $newlines" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
