#!/usr/bin/env bash
# Permanently redirecting requests to another page

# Install nginx
sudo apt update
sudo apt install -y nginx

# Create temporary file to store modified configuration
temp_config=$(mktemp)

# Add the desired redirection location block to the temporary file.
cat /etc/nginx/sites-available/default | sed '/^server {/a location \/redirect_me { return 301 http:\/\/github.com\/; }' > "$temp_config"

# Replace the original configuration with the modified configuration
sudo cp "$temp_config" /etc/nginx/sites-available/default

# Clean up the temporary file
rm "$temp_config"

# Restart nginx server
sudo service nginx restart
