#!/usr/bin/env bash
# Installs HAProxy server

sudo service haproxy stop
sudo apt-get purge -y haproxy

sudo apt update
sudo apt install -y haproxy

sudo sed -i '$aENABLED=1' /etc/default/haproxy

sudo sed -i '$a\\nfrontend http_front\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend http_back\n\nbackend http_back\n\tbalance roundrobin\n\tserver 272504-web-01 100.24.242.155:80 check\n\tserver 272504-web-02 52.86.39.45:80 check' /etc/haproxy/haproxy.cfg

sudo service haproxy restart
