#!/usr/bin/env bash
# This bash script displays:
# "To infinity and beyond" indefinitely
# With a sleep of 2 seconds between each iteration
# Then displays "I am invincible!!!" when it receives the SIGTERM signal

trap "echo 'I am invincible!!!'" SIGTERM
while true; do
    echo "To infinity and beyond"
    sleep 2
done
