#!/usr/bin/env bash
# This script displays the IP addresses the machine is run on
ipv4_addresses=$(ip -4 addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
for address in $ipv4_addresses; do
    echo "$address"
done
