#!/usr/bin/env bash
# This script runs the nginx as a regular user listening on port 8080 without superuser powers

# Set a user in the config by replacing '#user' with its value
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# Replace port 80 with port 8080 in the sites-available configuration file
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# Give owner permissions to read and write to the config file
chmod 644 /etc/nginx/nginx.conf
# Apache may interfere with nginx, so we kill the process if it is running
pkill apache2
# Now start the nginx service with the new nginx user
sudo -u nginx service nginx start
